# Generated by Django 4.1.4 on 2022-12-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Itme',
            new_name='Item',
        ),
    ]
