# Generated by Django 4.1.1 on 2022-10-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mID', models.PositiveIntegerField()),
                ('mType', models.CharField(max_length=8)),
                ('mCreatedBy', models.CharField(max_length=80)),
                ('mDateOfCreation', models.DateField()),
                ('mDaysPassed', models.PositiveSmallIntegerField()),
                ('mSolved', models.BooleanField()),
                ('mComment', models.CharField(max_length=500)),
            ],
        ),
    ]
